# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "el-hugo"
license = "BSD 3-Clause License"
licenselink = "https://github.com/ast3k/el-hugo/blob/main/LICENSE"
description = "a minimalist, fast and responsive hugo theme"
homepage = "https://github.com/ast3k/el-hugo"
tags = [
    "responsive",
    "simple",
    "clean",
    "light",
    "dark",
    "blog",
    "minimalist",
    "highlight.js",
    "search"
]
features = [
    "responsive",
    "single-column",
    "blog",
    "cover-image",
    "table-of-contents",
    "opengraph",
    "highlight.js",
    "favicon",
    "archive",
    "share-icons",
    "cover",
    "multilingual",
    "social-icons",
    "minified-assets",
    "theme-toggle",
    "menu-location-indicator",
    "scroll-to-top",
    "search"
]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.102.1"
    max = "0.102.1"

[author]
  name = "hugo"
  homepage = "https://github.com/ast3k"

# If porting an existing theme
[original]
  name = "el-hugo"
  homepage = "https://astrek.net"
  repo = "https://github.com/ast3k/el-hugo"
